export const ProjectData = [
  {
    id: 1,
    src: "assets/images/1.webp",
    title: "პროექტის შესახებ",
    description: `
      ოდესმე გიფიქრია პატარა ოთახზე, რომელში შესვლისას დროსა და სივრცეში იკარგები და საშუალება გეძლევა მომავლის გარკვეული ნაწილი დაინახო? ისეთი იმპულსები მიიღო, რომლებიც სუპერძალებს შეგძენდა?

      მოგესალმებით ილიაუნის კიბერლაბორატორია უნილაბში, რომელიც საშუალებას მოგცემს საკუთარ თავში ახალი შესაძლებლობები, ინტერესები და უნარები აღმოაჩინო, შენ ირგვლივ სამყაროს განვითარების ტემპს ყურადღება არ მიაქციო და თავს ისე შემოუძახო, რომ ხვალ უკვე დროს გაუსწრო და შენს გუშინდელ თავზე სინათლის წლით წინ იყო.
      
      აქ ყველა ერთად ვცდილობთ მომავალში ადამიანის როლს მნიშვნელობა შევძინოთ, რათა ერთი შეხედვით საშიშ, რობოტიზირებულ მომავალში ამომავალი წერტილი კვლავ ადამიანი იყოს. სივრცეში, რომელშიც მომავლის პროფესიები ჩვენთვის უმნიშვნელოვანესია და მათ გარეშე დროში მოგზაურობა მარსზე უჟანგბადოდ გარეშე გაფრენის ტოლფასია.`,
  },
  {
    id: 2,
    src: "assets/images/2.webp",
    title: "გთხოვთ, გაეცნოთ საიტის მოხმარების წესებსა და პირობებს",
    description: `
      მოგესალმებით ილიაუნის კიბერლაბორატორია უნილაბში, რომელიც საშუალებას მოგცემს საკუთარ თავში ახალი შესაძლებლობები, ინტერესები და უნარები აღმოაჩინო, შენ ირგვლივ სამყაროს განვითარების ტემპს ყურადღება არ მიაქციო და თავს ისე შემოუძახო, რომ ხვალ უკვე დროს გაუსწრო და შენს გუშინდელ თავზე სინათლის წლით წინ იყო.

      აქ ყველა ერთად ვცდილობთ მომავალში ადამიანის როლს მნიშვნელობა შევძინოთ, რათა ერთი შეხედვით საშიშ, რობოტიზირებულ მომავალში ამომავალი წერტილი კვლავ ადამიანი იყოს. `,
  },
  {
    id: 3,
    src: "assets/images/3.webp",
    title: "გთხოვთ, გაეცნოთ საიტის კონფიდენციალობის პოლიტიკას",
    description: `
      ოდესმე გიფიქრია პატარა ოთახზე, რომელში შესვლისას დროსა და სივრცეში იკარგები და საშუალება გეძლევა მომავლის გარკვეული ნაწილი დაინახო? ისეთი იმპულსები მიიღო, რომლებიც სუპერძალებს შეგძენდა?

       განვითარების ტემპს ყურადღება არ მიაქციო და თავს ისე შემოუძახო, რომ ხვალ უკვე დროს გაუსწრო და შენს გუშინდელ თავზე სინათლის წლით წინ იყო.

      აქ ყველა ერთად ვცდილობთ მომავალში ადამიანის როლს მნიშვნელობა შევძინოთ, რათა ერთი შეხედვით საშიშ, რობოტიზირებულ მომავალში ამომავალი წერტილი კვლავ ადამიანი იყოს. სივრცეში, რომელშიც მომავლის პროფესიები ჩვენთვის უმნიშვნელოვანესია და მათ გარეშე დროში მოგზაურობა მარსზე უჟანგბადოდ გარეშე გაფრენის ტოლფასია.`,
  },
];

export const studentData = [
  {
    id: 1,
    full_name: "Durward Arbuckle",
    status: "Sierra",
    points: 40,
    gender: "Male",
    personal_id: 41104402798,
    email: "darbuckle0@dagondesign.com",
    number: "411-942-0221",
    address: "7963 Norway Maple Parkway",
  },
  {
    id: 2,
    full_name: "Peggie Ditchett",
    status: "Alfa",
    points: 60,
    gender: "Female",
    personal_id: 31340184938,
    email: "pditchett1@sogou.com",
    number: "941-360-5033",
    address: "955 Lawn Drive",
  },
  {
    id: 3,
    full_name: "Joyann Jest",
    status: "Juliett",
    points: 98,
    gender: "Female",
    personal_id: "02361484782",
    email: "jjest2@addthis.com",
    number: "723-620-3294",
    address: "78769 Upham Alley",
  },
  {
    id: 4,
    full_name: "Yolande Catterell",
    status: "Romeo",
    points: 17,
    gender: "Female",
    personal_id: 43411953514,
    email: "ycatterell3@toplist.cz",
    number: "816-456-6961",
    address: "87 Sommers Road",
  },
  {
    id: 5,
    full_name: "Ozzie Norquay",
    status: "Zulu",
    points: 99,
    gender: "Male",
    personal_id: 41643958203,
    email: "onorquay4@icio.us",
    number: "699-508-9101",
    address: "1516 Dunning Point",
  },
  {
    id: 6,
    full_name: "Mathias Fearby",
    status: "Papa",
    points: 40,
    gender: "Male",
    personal_id: 64140321283,
    email: "mfearby5@illinois.edu",
    number: "360-182-6986",
    address: "6 Westridge Lane",
  },
  {
    id: 7,
    full_name: "Tori Kuhwald",
    status: "Zulu",
    points: 13,
    gender: "Female",
    personal_id: 82936495098,
    email: "tkuhwald6@rediff.com",
    number: "776-452-3316",
    address: "67 Clemons Drive",
  },
  {
    id: 8,
    full_name: "Gennifer Glennie",
    status: "Foxtrot",
    points: 79,
    gender: "Female",
    personal_id: 33956206392,
    email: "gglennie7@thetimes.co.uk",
    number: "944-195-9532",
    address: "69 Pierstorff Way",
  },
  {
    id: 9,
    full_name: "Michell Bricham",
    status: "Mike",
    points: 4,
    gender: "Female",
    personal_id: 58545295510,
    email: "mbricham8@illinois.edu",
    number: "682-511-9185",
    address: "220 Judy Alley",
  },
  {
    id: 10,
    full_name: "Batholomew Langlands",
    status: "Papa",
    points: 64,
    gender: "Male",
    personal_id: 27653959297,
    email: "blanglands9@ted.com",
    number: "564-179-8811",
    address: "0100 Waywood Road",
  },
  {
    id: 11,
    full_name: "Augusta Blabie",
    status: "Charlie",
    points: 30,
    gender: "Female",
    personal_id: 56463401089,
    email: "ablabiea@biblegateway.com",
    number: "986-268-7714",
    address: "9 Old Shore Road",
  },
  {
    id: 12,
    full_name: "Laure Ollenbuttel",
    status: "Alfa",
    points: 71,
    gender: "Female",
    personal_id: 22063897451,
    email: "lollenbuttelb@google.co.jp",
    number: "226-927-6014",
    address: "83 Bartillon Terrace",
  },
  {
    id: 13,
    full_name: "Shelli Gaul",
    status: "Zulu",
    points: 44,
    gender: "Female",
    personal_id: 39765119117,
    email: "sgaulc@elpais.com",
    number: "566-867-6294",
    address: "7058 Mariners Cove Hill",
  },
  {
    id: 14,
    full_name: "Adrea Baroch",
    status: "November",
    points: 6,
    gender: "Female",
    personal_id: 86765466067,
    email: "abarochd@people.com.cn",
    number: "621-388-6413",
    address: "25256 Charing Cross Point",
  },
  {
    id: 15,
    full_name: "Cathleen Searson",
    status: "Romeo",
    points: 71,
    gender: "Female",
    personal_id: 91527097501,
    email: "csearsone@china.com.cn",
    number: "933-967-7590",
    address: "8 Canary Avenue",
  },
  {
    id: 16,
    full_name: "Madelon Beatty",
    status: "Oscar",
    points: 90,
    gender: "Female",
    personal_id: 11807110418,
    email: "mbeattyf@tinyurl.com",
    number: "564-411-7299",
    address: "395 Coleman Park",
  },
  {
    id: 17,
    full_name: "Julia Joost",
    status: "India",
    points: 37,
    gender: "Female",
    personal_id: 81951404993,
    email: "jjoostg@angelfire.com",
    number: "191-299-4331",
    address: "22 Northland Place",
  },
  {
    id: 18,
    full_name: "Franciskus Scrowston",
    status: "Romeo",
    points: 59,
    gender: "Male",
    personal_id: 63343274303,
    email: "fscrowstonh@amazonaws.com",
    number: "648-521-3202",
    address: "31687 Meadow Ridge Drive",
  },
  {
    id: 19,
    full_name: "Shaina Yoakley",
    status: "India",
    points: 84,
    gender: "Female",
    personal_id: 67036919391,
    email: "syoakleyi@cmu.edu",
    number: "850-677-1846",
    address: "172 Lakewood Circle",
  },
  {
    id: 20,
    full_name: "Adamo Larvor",
    status: "Lima",
    points: 97,
    gender: "Male",
    personal_id: 62686848941,
    email: "alarvorj@wordpress.com",
    number: "307-202-4230",
    address: "3 Russell Court",
  },
  {
    id: 21,
    full_name: "Horatia Clayal",
    status: "Uniform",
    points: 91,
    gender: "Female",
    personal_id: "05113631966",
    email: "hclayalk@princeton.edu",
    number: "453-792-9564",
    address: "1 Heath Center",
  },
  {
    id: 22,
    full_name: "Mame Jesse",
    status: "Foxtrot",
    points: 25,
    gender: "Polygender",
    personal_id: 73850084135,
    email: "mjessel@dailymotion.com",
    number: "264-905-7740",
    address: "8040 Farwell Road",
  },
  {
    id: 23,
    full_name: "Burke Hassey",
    status: "Victor",
    points: 64,
    gender: "Male",
    personal_id: 11932867665,
    email: "bhasseym@ifeng.com",
    number: "553-215-0544",
    address: "39 Maywood Hill",
  },
  {
    id: 24,
    full_name: "Llywellyn Zupone",
    status: "Whiskey",
    points: 5,
    gender: "Male",
    personal_id: 34424038741,
    email: "lzuponen@ezinearticles.com",
    number: "906-920-7340",
    address: "5878 Southridge Road",
  },
  {
    id: 25,
    full_name: "Madelon Haversham",
    status: "Victor",
    points: 56,
    gender: "Female",
    personal_id: 30776617167,
    email: "mhavershamo@list-manage.com",
    number: "639-317-6396",
    address: "9 Maple Wood Hill",
  },
  {
    id: 26,
    full_name: "Kirsteni Firpo",
    status: "Alfa",
    points: 37,
    gender: "Female",
    personal_id: 97187357970,
    email: "kfirpop@example.com",
    number: "314-803-1717",
    address: "6 Coleman Parkway",
  },
  {
    id: 27,
    full_name: "Shandy Groarty",
    status: "X-ray",
    points: 71,
    gender: "Female",
    personal_id: "07570343913",
    email: "sgroartyq@edublogs.org",
    number: "237-463-6582",
    address: "5008 Northfield Crossing",
  },
  {
    id: 28,
    full_name: "Ewart Linklet",
    status: "Quebec",
    points: 26,
    gender: "Male",
    personal_id: 18669519864,
    email: "elinkletr@cafepress.com",
    number: "805-912-0440",
    address: "16 Grover Place",
  },
  {
    id: 29,
    full_name: "Tobiah Filewood",
    status: "Zulu",
    points: 25,
    gender: "Male",
    personal_id: 14495315665,
    email: "tfilewoods@ibm.com",
    number: "289-809-2524",
    address: "0 Beilfuss Parkway",
  },
  {
    id: 30,
    full_name: "Burnaby Paur",
    status: "Sierra",
    points: 76,
    gender: "Male",
    personal_id: 64320644810,
    email: "bpaurt@howstuffworks.com",
    number: "544-270-6588",
    address: "989 8th Parkway",
  },
  {
    id: 31,
    full_name: "Franchot Pegg",
    status: "Bravo",
    points: 42,
    gender: "Male",
    personal_id: 43997326153,
    email: "fpeggu@usatoday.com",
    number: "462-542-7378",
    address: "3 Mccormick Drive",
  },
  {
    id: 32,
    full_name: "Paloma Rusted",
    status: "India",
    points: 75,
    gender: "Female",
    personal_id: 22865856254,
    email: "prustedv@ow.ly",
    number: "263-788-7683",
    address: "23529 Bayside Hill",
  },
  {
    id: 33,
    full_name: "Norbert Sporgeon",
    status: "Delta",
    points: 23,
    gender: "Male",
    personal_id: 77494782330,
    email: "nsporgeonw@fastcompany.com",
    number: "572-112-8015",
    address: "16 Homewood Alley",
  },
  {
    id: 34,
    full_name: "Christin Starling",
    status: "Echo",
    points: 35,
    gender: "Female",
    personal_id: 24558131093,
    email: "cstarlingx@cam.ac.uk",
    number: "924-762-1348",
    address: "8911 Pierstorff Place",
  },
  {
    id: 35,
    full_name: "Ozzy Padly",
    status: "Uniform",
    points: 15,
    gender: "Male",
    personal_id: 43971381031,
    email: "opadlyy@nasa.gov",
    number: "633-726-0772",
    address: "91381 Annamark Plaza",
  },
  {
    id: 36,
    full_name: "Christina Yakolev",
    status: "Uniform",
    points: 25,
    gender: "Female",
    personal_id: 72741708014,
    email: "cyakolevz@cmu.edu",
    number: "576-598-7677",
    address: "049 Cody Lane",
  },
  {
    id: 37,
    full_name: "Sisile Duffie",
    status: "Tango",
    points: 26,
    gender: "Female",
    personal_id: 61216045114,
    email: "sduffie10@dailymail.co.uk",
    number: "721-139-0797",
    address: "6 Sugar Avenue",
  },
  {
    id: 38,
    full_name: "Zita Jeffryes",
    status: "Kilo",
    points: 20,
    gender: "Female",
    personal_id: "04875475864",
    email: "zjeffryes11@ted.com",
    number: "944-627-2921",
    address: "903 Ilene Point",
  },
  {
    id: 39,
    full_name: "Nels Vaggs",
    status: "Tango",
    points: 56,
    gender: "Male",
    personal_id: 28766475456,
    email: "nvaggs12@plala.or.jp",
    number: "304-565-9510",
    address: "22343 Lakewood Gardens Terrace",
  },
  {
    id: 40,
    full_name: "Artus Dollen",
    status: "Bravo",
    points: 79,
    gender: "Male",
    personal_id: "04410642021",
    email: "adollen13@friendfeed.com",
    number: "566-539-4088",
    address: "6 Maple Wood Hill",
  },
  {
    id: 41,
    full_name: "Fedora Cabrara",
    status: "Charlie",
    points: 75,
    gender: "Female",
    personal_id: 42040079149,
    email: "fcabrara14@myspace.com",
    number: "623-220-0800",
    address: "32096 Hoard Way",
  },
  {
    id: 42,
    full_name: "Aviva Ricketts",
    status: "Yankee",
    points: 83,
    gender: "Female",
    personal_id: 29394033206,
    email: "aricketts15@people.com.cn",
    number: "337-939-7790",
    address: "4 Hoard Street",
  },
  {
    id: 43,
    full_name: "Johan Vasilyonok",
    status: "Oscar",
    points: 13,
    gender: "Bigender",
    personal_id: 76607631187,
    email: "jvasilyonok16@issuu.com",
    number: "885-890-9862",
    address: "335 Warrior Place",
  },
  {
    id: 44,
    full_name: "Mariam Biggadike",
    status: "Mike",
    points: 71,
    gender: "Female",
    personal_id: 91240035555,
    email: "mbiggadike17@gnu.org",
    number: "764-863-2930",
    address: "789 Lakewood Park",
  },
  {
    id: 45,
    full_name: "Trudy MacCarroll",
    status: "Delta",
    points: 58,
    gender: "Female",
    personal_id: 50945282088,
    email: "tmaccarroll18@goodreads.com",
    number: "669-122-4601",
    address: "4614 Magdeline Court",
  },
  {
    id: 46,
    full_name: "Nani Woofinden",
    status: "Whiskey",
    points: 28,
    gender: "Female",
    personal_id: 88411122248,
    email: "nwoofinden19@wordpress.com",
    number: "617-427-7745",
    address: "3906 Straubel Alley",
  },
  {
    id: 47,
    full_name: "Curtis Doggrell",
    status: "November",
    points: 35,
    gender: "Agender",
    personal_id: 89800142069,
    email: "cdoggrell1a@skype.com",
    number: "491-654-9519",
    address: "0 Muir Hill",
  },
  {
    id: 48,
    full_name: "Lona Giddons",
    status: "Whiskey",
    points: 26,
    gender: "Female",
    personal_id: "09518752837",
    email: "lgiddons1b@amazon.co.jp",
    number: "186-763-9748",
    address: "8 American Ash Lane",
  },
  {
    id: 49,
    full_name: "Wyatan Dowding",
    status: "Foxtrot",
    points: 7,
    gender: "Male",
    personal_id: 71331407150,
    email: "wdowding1c@house.gov",
    number: "132-779-6516",
    address: "670 Crescent Oaks Circle",
  },
  {
    id: 50,
    full_name: "Elga Quince",
    status: "Romeo",
    points: 84,
    gender: "Female",
    personal_id: 83892293364,
    email: "equince1d@amazon.co.jp",
    number: "235-256-3325",
    address: "1 Fallview Alley",
  },
];
